//! errors

pub const ZdtError = FormatError || RangeError || TzError || TZifReadError || WinTzError;

pub const FormatError = error{
    EmptyString,
    InvalidCharacter,
    InvalidDirective,
    InvalidFormat,
    InvalidFraction,
    OutOfMemory,
    Overflow,
    ParseIntError,
    Underflow,
    UnsupportedOS,
};

pub const RangeError = error{
    DayOutOfRange,
    HourOutOfRange,
    MinuteOutOfRange,
    MonthOutOfRange,
    NanosecondOutOfRange,
    SecondOutOfRange,
    UnixOutOfRange,
    YearOutOfRange,
};

pub const TzError = error{
    AllTZRulesUndefined,
    AmbiguousDatetime,
    BadTZifVersion,
    CompareNaiveAware,
    InvalidIdentifier,
    InvalidOffset,
    InvalidPosixTz,
    InvalidTz,
    NonexistentDatetime,
    NotImplemented,
    TZifUnreadable,
    TzAlreadyDefined,
    TzUndefined,
};

pub const TZifReadError = error{
    AccessDenied,
    AntivirusInterference,
    BadHeader,
    BadPathName,
    BadVersion,
    BrokenPipe,
    Canceled,
    ConnectionResetByPeer,
    ConnectionTimedOut,
    DeviceBusy,
    EndOfStream,
    FileBusy,
    FileLocksNotSupported,
    FileNotFound,
    FileSystem,
    FileTooBig,
    InputOutput,
    InvalidUtf8,
    InvalidWtf8,
    IsDir,
    LockViolation,
    Malformed,
    NameTooLong,
    NetworkNotFound,
    NoDevice,
    NoSpaceLeft,
    NotDir,
    NotOpenForReading,
    NotSupported,
    OperationAborted,
    OutOfMemory,
    PathAlreadyExists,
    PermissionDenied,
    PipeBusy,
    ProcessFdQuotaExceeded,
    ProcessNotFound,
    SharingViolation,
    SocketNotConnected,
    StreamTooLong,
    SymLinkLoop,
    SystemFdQuotaExceeded,
    SystemResources,
    Unexpected,
    UnrecognizedVolume,
    WouldBlock,
};

pub const WinTzError = error{
    ReadRegistryFailed,
    TzNotFound,
    TzUtilFailed,
};
