name: zdt-tests

on:
  push:
    # branches: [master]
    tags: # run action on tag push only
      - "v*"
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  # build-tests-stable:
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, macos-latest, windows-latest]
  #   runs-on: ${{matrix.os}}
  #   steps:
  #     - uses: actions/checkout@main
  #     - uses: goto-bus-stop/setup-zig@v2
  #       with:
  #         version: 0.12.0
  #     - run: zig build tests
  build-tests-master:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      # - uses: actions/checkout@main
      # - uses: goto-bus-stop/setup-zig@v2
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
        with:
          version: master
      - run: zig build tests
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: goto-bus-stop/setup-zig@v2
      - run: zig fmt --check build.zig zdt.zig lib/**/*.zig tests/*.zig
